networks:
  service-network:

services:
  dev-frontend-service: &frontend-service
    build:
      context: .
      dockerfile: .docker/dev.Dockerfile
    env_file: ../.env
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
    networks:
      service-network:
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  prod-frontend-service: &frontend-service
    build:
      context: .
      dockerfile: .docker/prod.Dockerfile
    env_file: ../.env
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
    networks:
      service-network:
    # Exclude mounted volumes from dev image
    volumes: []